spring:
  profiles:
    active: dev
    include: jwt, gmail

  datasource:
    url: jdbc:mysql://localhost:3306/student_competency?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 8080

app:
  default-profile-image: /images/default-profile.png

logging:
  file:
    name: ./log/test.log  # 로그 파일 경로
  logback:
    rollingpolicy:
      max-history: 7  # 7일 이상된 로그 삭제
      max-file-size: 10MB   # 파일당 최대 10MB
